# Generated by Django 5.2.7 on 2025-11-06 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('kolicina', models.IntegerField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_prezime', models.CharField(max_length=100)),
                ('datum_rodjenja', models.DateField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='clanovi/')),
                ('krediti_voda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Obavestenje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=10)),
                ('poruka', models.TextField()),
                ('datum_slanja', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_app.clan')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_app.clan')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Uplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('to_date', models.DateField()),
                ('notification_sent', models.BooleanField(default=False)),
                ('meseci', models.IntegerField(default=1)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_app.clan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_trener', models.BooleanField(default=False)),
                ('is_klijent', models.BooleanField(default=False)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('sat', models.CharField(max_length=5)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klub_app.clan')),
            ],
            options={
                'unique_together': {('datum', 'sat', 'clan')},
            },
        ),
    ]
