# Generated by Django 5.2.7 on 2025-11-10 13:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klub_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='uplata',
            old_name='to_date',
            new_name='do_datum',
        ),
        migrations.AddField(
            model_name='uplata',
            name='od_datum',
            field=models.DateField(default=datetime.date(2025, 11, 10)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clan',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='sat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='kolicina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uplata',
            name='datum',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
