# Generated by Django 5.2.7 on 2025-11-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klub_app', '0002_rename_to_date_uplata_do_datum_uplata_od_datum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='tip',
            field=models.CharField(choices=[('Trener', 'Trener'), ('Klijent', 'Klijent')], default='Klijent', max_length=10),
        ),
        migrations.AlterField(
            model_name='clan',
            name='krediti_voda',
            field=models.FloatField(default=0.0),
        ),
    ]
